task: multi_crit_open_ended
test_split: open_ended
include: _default_template_yaml

metric_list:
  - metric: overall
    aggregation: !function utils.multi_crit_aggregate_overall
    higher_is_better: true
  - metric: completeness
    aggregation: !function utils.multi_crit_aggregate_completeness
    higher_is_better: true
  - metric: visual-grounding
    aggregation: !function utils.multi_crit_aggregate_visual_grounding
    higher_is_better: true
  - metric: hallucination
    aggregation: !function utils.multi_crit_aggregate_hallucination
    higher_is_better: true
  - metric: expressiveness
    aggregation: !function utils.multi_crit_aggregate_expressiveness
    higher_is_better: true
  - metric: clarity
    aggregation: !function utils.multi_crit_aggregate_clarity
    higher_is_better: true
  - metric: macro_avg
    aggregation: !function utils.multi_crit_aggregate_macro_avg
    higher_is_better: true
  - metric: pluralistic_acc
    aggregation: !function utils.multi_crit_aggregate_pluralistic_acc
    higher_is_better: true
  - metric: tradeoff_sensitivity
    aggregation: !function utils.multi_crit_aggregate_tradeoff_sensitivity
    higher_is_better: true
  - metric: conflict_matching
    aggregation: !function utils.multi_crit_aggregate_conflict_matching
    higher_is_better: true
