include: _default_yaml_template

task: cc_ocr_doc_parsing
dataset_name: doc_parsing

metric_list:
  - metric: doc_score
    aggregation: !function utils.cc_ocr_agg_dp_doc
    higher_is_better: true
  - metric: table_teds
    aggregation: !function utils.cc_ocr_agg_dp_table
    higher_is_better: true
  - metric: formula_score
    aggregation: !function utils.cc_ocr_agg_dp_formula
    higher_is_better: true
  - metric: molecular_score
    aggregation: !function utils.cc_ocr_agg_dp_molecular
    higher_is_better: true
  - metric: overall_score
    aggregation: !function utils.cc_ocr_agg_dp_overall
    higher_is_better: true

metadata:
  - version: 0.0
