dataset_path: WangYipu2002/CrossPoint-Bench
task: crosspoint_bench
test_split: train
output_type: generate_until
doc_to_visual: !function utils.crosspoint_doc_to_visual
doc_to_text: !function utils.crosspoint_doc_to_text
doc_to_target: !function utils.crosspoint_doc_to_target

generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

process_results: !function utils.crosspoint_process_results
metric_list:
  - metric: crosspoint_accuracy
    aggregation: !function utils.crosspoint_aggregate_overall
    higher_is_better: true
  - metric: fine_grained_grounding
    aggregation: !function utils.crosspoint_aggregate_fine_grained_grounding
    higher_is_better: true
  - metric: visibility_reasoning
    aggregation: !function utils.crosspoint_aggregate_visibility_reasoning
    higher_is_better: true
  - metric: correspondence_judgement
    aggregation: !function utils.crosspoint_aggregate_correspondence_judgement
    higher_is_better: true
  - metric: correspondence_pointing
    aggregation: !function utils.crosspoint_aggregate_correspondence_pointing
    higher_is_better: true
  - metric: level_object
    aggregation: !function utils.crosspoint_aggregate_level_object
    higher_is_better: true
  - metric: level_part
    aggregation: !function utils.crosspoint_aggregate_level_part
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  version: 0.1
