dataset_path: RadGenome/PMC-VQA
dataset_kwargs:
  data_files:
    test: test_2.csv
task: pmc_vqa
test_split: test
output_type: generate_until

doc_to_visual: !function utils.pmc_vqa_doc_to_visual
doc_to_text: !function utils.pmc_vqa_doc_to_text
doc_to_target: !function utils.pmc_vqa_doc_to_target

generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

process_results: !function utils.pmc_vqa_process_results

metric_list:
  - metric: accuracy
    aggregation: !function utils.agg_mean
    higher_is_better: true

metadata:
  version: 0.0
