task: c4_bench_e0
task_alias: E0 Free Answer and Explanation
include: _default_template_yaml
process_docs: !function utils.c4_process_docs_e0
metric_list:
  - metric: c4_exact_match
    aggregation: mean
    higher_is_better: true
  - metric: c4_json_valid
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  task_form: E0
