dataset_path: chanhee-luke/RoboSpatial-Home
output_type: generate_until
process_docs: !function utils.robo_spatial_process_docs
doc_to_visual: !function utils.robo_spatial_doc_to_visual
doc_to_text: !function utils.robo_spatial_doc_to_text
doc_to_target: !function utils.robo_spatial_doc_to_answer
process_results: !function utils.robo_spatial_process_results_generation
metric_list:
  - metric: robo_spatial_score
    aggregation: !function utils.robo_spatial_aggregate_score
    higher_is_better: true
metadata:
  version: 0.1
