dataset_path: ouyanglinke/OmniDocBench_tsv
dataset_kwargs:
  token: True
task: omnidocbench
tag:
  - public_eval_qwen3_5_family
  - public_eval_seed2_family
  - public_eval_gemini3_family
test_split: train
output_type: generate_until
doc_to_visual: !function utils.omnidocbench_doc_to_visual
doc_to_text: !function utils.omnidocbench_doc_to_text
doc_to_target: !function utils.omnidocbench_doc_to_target
generation_kwargs:
  max_new_tokens: 4096
  temperature: 0
  do_sample: false
process_results: !function utils.omnidocbench_process_results
metric_list:
  - metric: omnidocbench_overall
    aggregation: !function utils.omnidocbench_aggregate_overall
    higher_is_better: true
  - metric: omnidocbench_text_edit
    aggregation: !function utils.omnidocbench_aggregate_text_edit
    higher_is_better: false
  - metric: omnidocbench_table_teds
    aggregation: !function utils.omnidocbench_aggregate_table_teds
    higher_is_better: true
  - metric: omnidocbench_formula_edit
    aggregation: !function utils.omnidocbench_aggregate_formula_edit
    higher_is_better: false
  - metric: omnidocbench_text_edit_en
    aggregation: !function utils.omnidocbench_aggregate_text_edit_en
    higher_is_better: false
  - metric: omnidocbench_text_edit_cn
    aggregation: !function utils.omnidocbench_aggregate_text_edit_cn
    higher_is_better: false
  - metric: omnidocbench_table_teds_en
    aggregation: !function utils.omnidocbench_aggregate_table_teds_en
    higher_is_better: true
  - metric: omnidocbench_table_teds_cn
    aggregation: !function utils.omnidocbench_aggregate_table_teds_cn
    higher_is_better: true
  - metric: omnidocbench_formula_edit_en
    aggregation: !function utils.omnidocbench_aggregate_formula_edit_en
    higher_is_better: false
  - metric: omnidocbench_formula_edit_cn
    aggregation: !function utils.omnidocbench_aggregate_formula_edit_cn
    higher_is_better: false
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 1.0
