dataset_path: json
dataset_kwargs:
  data_files:
    test: "https://openaipublic.blob.core.windows.net/simple-evals/healthbench/2025-05-07-06-14-12_oss_eval.jsonl"
task: healthbench
test_split: test
output_type: generate_until

doc_to_messages: !function utils.healthbench_doc_to_messages
doc_to_visual: !function utils.healthbench_doc_to_visual
doc_to_text: !function utils.healthbench_doc_to_text
doc_to_target: !function utils.healthbench_doc_to_target

generation_kwargs:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 1.0
  do_sample: true

process_results: !function utils.healthbench_process_results

metric_list:
  - metric: healthbench_score
    aggregation: !function utils.agg_clipped_mean
    higher_is_better: true

metadata:
  version: 0.0
