include: healthbench.yaml
task: healthbench_consensus
dataset_kwargs:
  data_files:
    test: "https://openaipublic.blob.core.windows.net/simple-evals/healthbench/consensus_2025-05-09-20-00-46.jsonl"
