dataset_path: nv-njb/OpenXVQA
task: openxvqa
test_split: test
output_type: generate_until
doc_to_visual: !function utils.openxvqa_doc_to_visual
doc_to_text: !function utils.openxvqa_doc_to_text
doc_to_target: !function utils.openxvqa_doc_to_target
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.openxvqa_process_results
metric_list:
  - metric: openxvqa_accuracy
    aggregation: !function utils.openxvqa_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly and only give the best option. The best answer is: "
metadata:
  version: 0.1
