include: _default.yaml
doc_to_visual: !function mcq_utils.videonet_mcq_doc_to_visual
doc_to_text: !function mcq_utils.videonet_mcq_doc_to_text
doc_to_messages: !function mcq_utils.videonet_mcq_doc_to_messages
generation_kwargs:
  temperature: 0
  do_sample: False
  max_new_tokens: 8192
process_results: !function mcq_utils.videonet_mcq_process_results
metric_list:
  - metric: mcq_acc
    aggregation: !function mcq_utils.videonet_mcq_aggregate_results
    higher_is_better: True
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  version: 0.0
