task: "xmod_bench_lite_a2v"

dataset_kwargs:
  data_files: hf://datasets/RyanWW/XModBench/data_lite/a2v.jsonl

doc_to_visual: !function utils.xmod_bench_doc_to_visual
doc_to_text: !function utils.xmod_bench_doc_to_text
doc_to_messages: !function utils.xmod_bench_doc_to_messages
doc_to_target: "correct_answer"
process_results: !function utils.xmod_bench_process_results

include: _default_template_yaml
